controller_manager:
  ros__parameters:
    update_rate: 500

    lqr_controller:
      type: lqr_controller/LQRController

lqr_controller:
  ros__parameters:
    use_sim_time: true
    imu_topic: /imu_imu_sensor/imu
    imu_pose_topic: /imu_pose_sensor/pose
    cmd_vel_topic: /cmd_vel
    effort_limit: 20.0
    desired_height: 0.21
    mode: 0
    q_diag: [10.0, 400.0, 100.0, 40.0, 600.0, 50.0]
    r_diag: [8.0, 0.5]
